version: 2.1
##Add the orbs stanza below your version, invoking the orb:
orbs:

  slack: circleci/slack@4.1

jobs:



  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm i
            npm run build

      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
             cd backend
             npm i
             npm run build

      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

  test-frontend:
    docker:
      - image : circleci/node:13.8.0
    steps:
     - checkout
     - restore_cache:
          keys: [test-frontend]     
     - run:
        command : |
          cd frontend
          npm i
          npm run test

     - save_cache:
          paths: [test-frontend]
          key: backend-build
                
  test-backend:
    docker:
      - image : circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [test-backend]     
      - run:
         command : |
           cd backend
           npm i
           npm run test

      - save_cache:
          paths: [test-backend]
          key: backend-build

  scan-frontend:
    docker:
      - image : circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [scan-frontend]   
      - run:
         command : |
           cd frontend
           npm i
           npm audit fix --force
           npm audit fix --force


      - save_cache:
          paths: [scan-frontend]
          key: backend-build



  scan-backend:
    docker:
      - image : circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [scan-backend]  
      - run:
         command : |
           cd backend
           npm i
           npm audit fix --force
           npm audit fix --force


      - save_cache:
          paths: [scan-backend]
          key: backend-build


## slack notification job
  deploy:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command:
           npm i
           npm run deploy
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: fail
          template: basic_fail_1
          exit 1


workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
         requires: [build-frontend]
      - test-backend:
         requires: [build-backend]
      - scan-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
      - deploy:
          context: cdond-c3-projectstarter  

      

